package projson.modelo


private const val QUOTE = "\""
private const val COMMA = ","

/**
 * [JsonVisitor] implementation that renders a JSON model tree as compact JSON text.
 *
 * The visitor walks through [JsonValue] instances and appends their textual representation to an
 * internal [StringBuilder]. Object properties are rendered in sorted key order to make the output
 * deterministic.
 */
class JsonStringVisitor : JsonVisitor {
    private val builder = StringBuilder()

    /**
     * Returns the JSON text generated by the visits performed so far.
     *
     * @return compact JSON string.
     */
    fun result(): String = builder.toString()

    /**
     * Renders a [JsonNull] value.
     *
     * @param value null value to render.
     */
    override fun visitNull(value: JsonNull) {
        builder.append("null")
    }

    /**
     * Renders a [JsonString] value with JSON escaping.
     *
     * @param value string value to render.
     */
    override fun visitString(value: JsonString) {
        builder.append(QUOTE)
            .append(value.value.escapeJsonString())
            .append(QUOTE)
    }

    /**
     * Renders a [JsonNumber] value.
     *
     * @param value number value to render.
     */
    override fun visitNumber(value: JsonNumber) {
        builder.append(value.value)
    }

    /**
     * Renders a [JsonBoolean] value.
     *
     * @param value boolean value to render.
     */
    override fun visitBoolean(value: JsonBoolean) {
        builder.append(value.value)
    }

    /**
     * Renders a [JsonArray] and all its elements.
     *
     * @param value array value to render.
     */
    override fun visitArray(value: JsonArray) {
        builder.append("[")
        val items = value.elements.iterator()
        while (items.hasNext()) {
            items.next().accept(this)
            if (items.hasNext()) {
                builder.append(COMMA)
            }
        }
        builder.append("]")
    }

    /**
     * Renders a [JsonObject] and all its properties.
     *
     * @param value object value to render.
     */
    override fun visitObject(value: JsonObject) {
        builder.append("{")
        val fields = value.properties.toSortedMap().iterator()
        while (fields.hasNext()) {
            val field = fields.next()
            builder.append(QUOTE)
                .append(field.key.escapeJsonString())
                .append("\":")
            field.value.accept(this)
            if (fields.hasNext()) {
                builder.append(COMMA)
            }
        }
        builder.append("}")
    }
}

private fun String.escapeJsonString(): String {
    val original = this

    return buildString {
        for (ch in original) {
            when (ch) {
                '"' -> append("\\\"")
                '\\' -> append("\\\\")
                '\b' -> append("\\b")
                '\u000C' -> append("\\f")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\t' -> append("\\t")
                else -> {
                    if (ch < ' ') {
                        append("\\u%04x".format(ch.code))
                    } else {
                        append(ch)
                    }
                }
            }
        }
    }
}